# additional cameras for Kitchen L environment
static_camera_list:
- name: countertop_camera  # elevated overhead, looking down at full table
  type: D435
  position:
  - 0.0
  - -0.50
  - 2.2
  forward:
  - 0
  - 0.45
  - -1.0
  left:
  - -1
  - 0
  - 0
